### ISSUE TITLE
Build failure with time 1.4

### ISSUE THREAD

**Issue by snoyberg** [chrisdone/pdfinfo#11]
Unpacking to pdfinfo-1.5.3/
Resolving dependencies...
Configuring pdfinfo-1.5.3...
Building pdfinfo-1.5.3...
Preprocessing library pdfinfo-1.5.3...
[1 of 1] Compiling Text.PDF.Info    ( src/Text/PDF/Info.hs, dist/build/Text/PDF/Info.o )

src/Text/PDF/Info.hs:155:18: Not in scope: ‘defaultTimeLocale’

**Comment by chrisdone** [comment]
I switched to `time-locale-compat` in 1.5.4. Tested on GHC 7.8.4 and 7.10.

**Comment by snoyberg** [comment]
Stackage build confirms this as fixed :)
